//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class lsCommonEntities : DbContext
    {
        public lsCommonEntities()
            : base("name=lsCommonEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<stp_wf_rss_scs_SPM_GridInformationTable_Result> stp_wf_rss_scs_SPM_GridInformationTable(string contentType, string divisionCode, string regionCode, string companyCode, string oUCode, string searchKey, string username, Nullable<int> year, Nullable<int> month, Nullable<int> week, string productCode, string salesmanCode)
        {
            var contentTypeParameter = contentType != null ?
                new ObjectParameter("ContentType", contentType) :
                new ObjectParameter("ContentType", typeof(string));
    
            var divisionCodeParameter = divisionCode != null ?
                new ObjectParameter("DivisionCode", divisionCode) :
                new ObjectParameter("DivisionCode", typeof(string));
    
            var regionCodeParameter = regionCode != null ?
                new ObjectParameter("RegionCode", regionCode) :
                new ObjectParameter("RegionCode", typeof(string));
    
            var companyCodeParameter = companyCode != null ?
                new ObjectParameter("CompanyCode", companyCode) :
                new ObjectParameter("CompanyCode", typeof(string));
    
            var oUCodeParameter = oUCode != null ?
                new ObjectParameter("OUCode", oUCode) :
                new ObjectParameter("OUCode", typeof(string));
    
            var searchKeyParameter = searchKey != null ?
                new ObjectParameter("SearchKey", searchKey) :
                new ObjectParameter("SearchKey", typeof(string));
    
            var usernameParameter = username != null ?
                new ObjectParameter("Username", username) :
                new ObjectParameter("Username", typeof(string));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var weekParameter = week.HasValue ?
                new ObjectParameter("Week", week) :
                new ObjectParameter("Week", typeof(int));
    
            var productCodeParameter = productCode != null ?
                new ObjectParameter("ProductCode", productCode) :
                new ObjectParameter("ProductCode", typeof(string));
    
            var salesmanCodeParameter = salesmanCode != null ?
                new ObjectParameter("SalesmanCode", salesmanCode) :
                new ObjectParameter("SalesmanCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_wf_rss_scs_SPM_GridInformationTable_Result>("stp_wf_rss_scs_SPM_GridInformationTable", contentTypeParameter, divisionCodeParameter, regionCodeParameter, companyCodeParameter, oUCodeParameter, searchKeyParameter, usernameParameter, yearParameter, monthParameter, weekParameter, productCodeParameter, salesmanCodeParameter);
        }
    }
}
